#!/bin/bash
set -uex

# build the builder image
./script/build

# create the binary
docker run -ti -v ${PWD}:/code sebglazebrook/dot-com cargo build --release

cp target/release/dot-com .

# build a new image with that binary
docker build --tag sebglazebrook/dot-com  --file dockerfiles/Dockerfile.release .
